version: "3.8"

services:
  php:
    build: ./php # /php配下のDockerfileを参照させる
    container_name: "php"
    volumes:
      - ./src/laravel:/var/www/html # マウント先を指定(src/laravel以下が本体)

  nginx:
    container_name: nginx
    image: nginx
    ports:
      - "8080:80"
    volumes:
       - ./src/laravel:/var/www/html
       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # nginxの設定(詳細は/nginx/default.confを確認)
    working_dir: /var/www/html

  front:
    build:
      context: ./nuxt # /nuxt配下のDockerfileを参照させる
      args:
        WORKDIR: $WORKDIR
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_PORT"
    command: yarn run dev
    volumes:
      - "./src/nuxt:/$WORKDIR"
    ports:
      - "$FRONT_PORT:3000"
    depends_on:
      - php
